import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import Footer from "@/Component/Footer";
import CustomCursor from "@/Component/CustomCursor";
import Transition from "@/Component/Transition";

const fontSans = Mona_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PT.MLM",
  description: "Generated by create next app",
  icons: "./ptmlm.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.className} text-[#F2EFE7]  antialiased bg-[#F2EFE7]`}>
        <Navbar />
        <CustomCursor />
        <Transition>
          {children}
          <Footer />
        </Transition>
      </body>
    </html>
  );
}
